/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ["class"],
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}", "./.storybook/**/*.{js,ts,jsx,tsx,mdx}"],
    theme: {
        extend: {
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            colors: {
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                chart: {
                    1: "hsl(var(--chart-1))",
                    2: "hsl(var(--chart-2))",
                    3: "hsl(var(--chart-3))",
                    4: "hsl(var(--chart-4))",
                    5: "hsl(var(--chart-5))",
                },
                lightGreen: "#E9FFEF",
                point: "#05BE71",
                lightRed: "#FFF4F3",
                red: "#EA4335",
                darkGray: "#626262",
                gray: "#828387",
                lightGray: "#B7B7B7",
                chat: "#EDEDED",
                back: "#FAFAFA",
                white: "#fff",
                black: "#000",
                yellow: "#FDE500",
                lightPurple: "#E6E6FA",
                purple: "#7878FF",
                skyBlue: "#e6f5ff",
                blue: "#28AEFF",
                darkBlue: "#0040FF",
                telegram: "#0088cc",
            },
        },
        colors: {
            lightGreen: "#E9FFEF",
            point: "#05BE71",
            lightRed: "#FFF4F3",
            red: "#EA4335",
            darkGray: "#626262",
            gray: "#828387",
            lightGray: "#B7B7B7",
            chat: "#EDEDED",
            white: "#fff",
            black: "#000",
            yellow: "#FDE500",
            lightPurple: "#E6E6FA",
            purple: "#7878FF",
            skyBlue: "#e6f5ff",
            blue: "#28AEFF",
            darkBlue: "#0040FF",
            telegram: "#0088cc",
        },
    },
    plugins: [require("tailwindcss-animate"), require("tailwind-scrollbar"), require("tailwind-scrollbar-hide")],
};
